name: Auto Collect VPN Configs

on:
  schedule:
    - cron: '0 */12 * * *'  # هر ۱۲ ساعت اجرا میشه
  workflow_dispatch:        # امکان اجرای دستی هم داره

permissions:
  contents: write

jobs:
  collect:
    runs-on: ubuntu-latest
    env:
      VPN_REPOS: ${{ secrets.VPN_REPOS }}   # ریپوزیتوری‌ها رو مخفی نگه میداره
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install requirements
        run: pip install requests

      - name: Run collector script
        run: python collector.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add configs/
          git commit -m "🔄 Auto update configs" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
